import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import '@/styles/main.scss';
import WindowSizeContextProvider from '@/app/WindowSizeContextProvider';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en" data-font_weightiness="thinner">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />
        <meta name="robots" content="noindex, nofollow"/>
        <title>IMIKO</title>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        <meta
          name="description"
          content="IMIKO"
        />
      </head>
      <WindowSizeContextProvider>
        <body className={inter.className}>
          {children}
          <div id="portal" />
        </body>
      </WindowSizeContextProvider>
    </html>
  );
}
